const CATEGORIES_KEY = "theo-stracke-support-categories";

const DEFAULT_CATEGORIES: string[] = [
  "ADEMAR DESPACHANTE",
  "AR REDE VELLUM",
  "ATIVA DESPACHANTE",
  "BLUE DESPACHANTE",
  "CAMBORIU DESPACHANTE",
  "CENTER DESPACHANTE",
  "COMPETENCIA CONTABILIDADE E PERICIAS",
  "CONTABILIDADE E DESPACHANTE COLOMBI",
  "CONTABILIDADE SIGRID",
  "COUTO DESPACHANTE",
  "DALLABRIDA DESPACHANTE E CONTABILIDADE",
  "DARCI CIDADE",
  "DEPACHANTE FUMACENSE",
  "DESPACHANTE 7",
  "DESPACHANTE ABBA",
  "DESPACHANTE AGILIZA",
  "DESPACHANTE AGILIZZE",
  "DESPACHANTE AGRONOMICA",
  "DESPACHANTE AGUAS MORNAS",
  "DESPACHANTE ALEMAO",
  "DESPACHANTE ALVORADA",
  "DESPACHANTE APOLO",
  "DESPACHANTE ARIRIU FABIANO",
  "DESPACHANTE AURORA",
  "DESPACHANTE AZEVEDO",
  "DESPACHANTE BARON",
  "DESPACHANTE BENTE-VI",
  "DESPACHANTE BETO DEHON",
  "DESPACHANTE BETO",
  "DESPACHANTE BONASSA",
  "DESPACHANTE CABRAL",
  "DESPACHANTE CADI",
  "DESPACHANTE CAMPECHE",
  "DESPACHANTE CANGUCU",
  "DESPACHANTE CANOAS",
  "DESPACHANTE CAPITAL",
  "DESPACHANTE CATAPAM",
  "DESPACHANTE CELSO",
  "DESPACHANTE CENTRAL",
  "DESPACHANTE CICERO",
  "DESPACHANTE CILO",
  "DESPACHANTE CIPRIANI",
  "DESPACHANTE CLAUDINO",
  "DESPACHANTE DANILO",
  "DESPACHANTE DA PONTE",
  "DESPACHANTE DE LUCIO",
  "DESPACHANTE DE TRANSITO INGLESES",
  "DESPACHANTE DUDU",
  "DESPACHANTE EXPRESS",
  "DESPACHANTE FERREIRA LTDA",
  "DESPACHANTE FLORIANI",
  "DESPACHANTE FRECCIA",
  "DESPACHANTE GARCIA",
  "DESPACHANTE GODINHO ROSITA",
  "DESPACHANTE GOMES",
  "DESPACHANTE GRAVATA",
  "DESPACHANTE GRAVATAL",
  "DESPACHANTE GUABIRUBENSE",
  "DESPACHANTE GUENTHER",
  "DESPACHANTE HORIZONTE",
  "DESPACHANTE ITOUPAVA",
  "DESPACHANTE JOHNI",
  "DESPACHANTE JUNIOR",
  "DESPACHANTE KAKA",
  "DESPACHANTE LOHN",
  "DESPACHANTE LONTRAS",
  "DESPACHANTE LUCIO",
  "DESPACHANTE MAFRA",
  "DESPACHANTE MARCELINO",
  "DESPACHANTE MARIA JOSE",
  "DESPACHANTE MARLISE",
  "DESPACHANTE MAX",
  "Despachante Melchioretto",
  "DESPACHANTE MIKIMBA",
  "DESPACHANTE MODELO",
  "DESPACHANTE MORRETES",
  "DESPACHANTE PALHOCA",
  "DESPACHANTE PAULINHO",
  "DESPACHANTE PETRY",
  "Despachante Pierri",
  "DESPACHANTE PINGUIM",
  "DESPACHANTE PONTUAL",
  "DESPACHANTE POPULAR",
  "DESPACHANTE PRECISAO LTDA",
  "Despachante Raupp",
  "DESPACHANTE RIBEIRO",
  "DESPACHANTE RIEDI",
  "DESPACHANTE ROCA",
  "DESPACHANTE ROUSSENQ",
  "DESPACHANTE SANTA ROSA",
  "DESPACHANTE SCHMIDT",
  "DESPACHANTE SEM PARAR",
  "DESPACHANTE SESTREM",
  "DESPACHANTE SILVA",
  "DESPACHANTE SILVEIRA",
  "DESPACHANTE TUBARAO",
  "DESPACHANTE VOLANTE",
  "DESPACHANTE XANDE",
  "Despachante Zanoni",
  "DIGITAL DESPACHANTES",
  "D. L. A. - SERVICOS DE PREPARACAO DE DOCUMENTOS",
  "DVS DESPACHANTE",
  "EDSON DESPACHANTE",
  "EMPLACAR DESPACHANTE",
  "EXPRESS.DOC DESPACHANTE LTDA",
  "EXPRESSO DESPACHANTE",
  "GELSON NANDI",
  "GILSON EGGERS DESPACHANTE",
  "ITACU DESPACHANTE",
  "KIDO DESPACHANTE",
  "KIKO DESPACHANTE",
  "LEO DESPACHANTE",
  "LOTERICA MARCARINI",
  "MARCOS DESPACHANTE",
  "M ROCHA DESPACHANTE",
  "OFFICECAR DESPACHANTE",
  "RDA ACESSORIA DE TRANSITO",
  "REESE DESPACHANTE",
  "REGIUM",
  "ROBERTO DESPACHANTE",
  "SIMPLIFICA RECURSOS DE MULTAS",
  "S & N DESPACHANTE",
  "SONAGLI ASSESSORIA",
  "UNIAOCERT CERTIFICACAO E PROCURACOES DIGITAIS",
  "VIDA BOA",
];

export function loadCategories(): string[] {
  try {
    const raw = localStorage.getItem(CATEGORIES_KEY);
    const list = raw ? (JSON.parse(raw) as string[]) : DEFAULT_CATEGORIES;
    // Dedup e ordena por ordem de inserção (mantendo default primeiro)
    const seen = new Set<string>();
    const merged = [...DEFAULT_CATEGORIES, ...list].filter((c) => {
      const key = c.trim();
      if (!key || seen.has(key)) return false;
      seen.add(key);
      return true;
    });
    return merged;
  } catch {
    return DEFAULT_CATEGORIES;
  }
}

export function saveCategories(categories: string[]) {
  const cleaned = Array.from(new Set(categories.map((c) => c.trim()).filter(Boolean)));
  localStorage.setItem(CATEGORIES_KEY, JSON.stringify(cleaned));
}

export function addCategory(newCategory: string) {
  const list = loadCategories();
  const value = newCategory.trim();
  if (!value || list.includes(value)) return list;
  const next = [...list, value];
  saveCategories(next);
  return next;
}
